const express = require('express')
const { addProduct, getProducts, removeProducts, getProductReview, getProductByCategory, getAllOrders, getProductById, addProductQuantity, removeProductQuantity, calculateRating, getProductByCategory1And2, getAllReturns, searchProducts, displayPagination, searchSections, mainSearchPage} = require('../controller/productController')
const { authUser, checkAdmin } = require('../middleware/authenticate')
const router = express.Router()

router.route('/add').post(authUser,checkAdmin,addProduct)
router.route('/show').get(getProducts)
router.route('/delete/:id').delete(authUser,checkAdmin,removeProducts)
router.route('/show/:category').get(getProductByCategory)
router.route('/review/:id').get(getProductReview)
router.route('/order/all').get(authUser,checkAdmin,getAllOrders)
router.route('/returns').get(authUser,checkAdmin,getAllReturns)
router.route('/product/:id').get(getProductById)
router.route('/add/product/quantity').put(addProductQuantity)
router.route('/remove/product/quantity').put(removeProductQuantity)
router.route('/category').get(getProductByCategory1And2)
router.route('/product/rate/:id').put(calculateRating)
router.route('/search/product/').get(searchProducts)
router.route('/search/section/').get(searchSections)
router.route('/search/main/:category/:category1/:category2/:category3/:category4/:category5').get(mainSearchPage)    
router.route('/display/pagination').get(authUser,checkAdmin,displayPagination)
module.exports = router